[tool.poetry]
name = "patterns"
version = "0.1.0"
description = ""
authors = ["back7 <back7@dev.lan>"]

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
